config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: ifca_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/saps-deploy-test:
      branch: master
      repo: https://github.com/orviz/saps-deploy-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  SvcQC.Dep:
    repos:
      github.com/orviz/saps-deploy-test ec3_client:
        commands:
        - /usr/bin/env sh .sqa/script.homey-myrtle-skunk.sh
        container: svcqc.dep_muggy-cream-bordeaux
timeout: 1800
